# Understanding tensorflow 1x

In [2]:
import tensorflow as tf

message = tf.constant('Welcome to the exciting world of Neural Networks')

# with tf.Session() as sess:
#     print(sess.run(message).decode)

### Constants

In [4]:
t_1 = tf.constant(4)
print(t_1)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
t_2 = tf.constant([4,3,2])
t_2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 3, 2])>

In [7]:
zero_t = tf.zeros([2,3],tf.int32)
print(zero_t)#visualizando tensor
print(zero_t.shape)# visualizando shape

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
(2, 3)


### Sequences

In [8]:
range_t = tf.linspace(2.0,5.0,5)#tf.linspace(start, stop, num) // The corresponding values differ by (stop-start)/(num-1)
range_t

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([2.  , 2.75, 3.5 , 4.25, 5.  ], dtype=float32)>

In [10]:
range_t = tf.range(10)
range_t

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

### Random tensors

In [12]:
# t_random = tf.random_normal([2,3],mean=2.0,stddev=4,seed=12)
# t_random'