# Undertanding TF2

### AutoGraph

In [1]:
import tensorflow as tf

In [3]:
def linear_layer(x):
    return 3 * x +2

@tf.function
def simple_nn(x):
    return tf.nn.relu(linear_layer(x))

def simple_function(x):
    return 3*x

simple_nn(3)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

#### tf.function decorator

In [1]:
import tensorflow as tf
import timeit

In [2]:
cell = tf.keras.layers.LSTMCell(100)

In [3]:
@tf.function
def fn(input,state):
    return cell(input,state)

In [4]:
input = tf.zeros([100,100])
state = [tf.zeros([100,100])]*2

In [5]:
cell(input,state)
fn(input,state)

(<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 [<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
  <tf.Tensor: shape=(100, 100), dtype=float32, numpy=
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>])

In [11]:
graph_time = timeit.timeit(lambda: cell(input,state),number=100)
auto_graph_time = timeit.timeit(lambda: fn(input,state), number=100)
print('graph time: ',graph_time)
print('auto graph time: ',auto_graph_time)

graph time:  0.24218419999999696
auto graph time:  0.11213329999998223
